"""PdfSuite — the full document/PDF toolbox, integrated (reportlab).

The second integrated *program*: a complete PDF generator — multi-page documents,
headings, paragraphs, tables, embedded images — reachable as ONE capability set
through the Connector protocol, so the whole suite flows through ``orchestrate``
like any other capability.

Fail-safe and isolated: outputs land in a temp dir; a failing operation returns
not-ok with the real error.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
from reportlab.lib.styles import getSampleStyleSheet  # type: ignore[import-untyped]
from reportlab.platypus import (  # type: ignore[import-untyped]
    Image as RLImage,
)
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
)

from universal_mind.connectors import ConnectorResult


class PdfSuite:
    """The integrated reportlab capability surface (a complete PDF program)."""

    name = "pdf-suite"
    capability = "pdf"

    OPERATIONS = ("document", "table", "with_image")

    def document(
        self,
        title: str = "Universal Mind Report",
        sections: list[str] | None = None,
        out_dir: str | None = None,
    ) -> dict[str, Any]:
        """Build a real multi-section PDF document."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "document.pdf"
        styles = getSampleStyleSheet()
        story: list[Any] = [Paragraph(title, styles["Title"])]
        for section in sections or ["Generated by the Universal Mind synthesis loop."]:
            story.append(Spacer(1, 12))
            story.append(Paragraph(section, styles["BodyText"]))
        try:
            SimpleDocTemplate(str(out_path), pagesize=A4).build(story)
        except Exception as exc:  # noqa: BLE001 — real generation errors surface
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}

    def table(
        self,
        headers: list[str] | None = None,
        rows: list[list[str]] | None = None,
        out_dir: str | None = None,
    ) -> dict[str, Any]:
        """Build a real PDF containing a data table."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "table.pdf"
        data = [headers or ["Column A", "Column B"]]
        data.extend(rows or [["1", "2"], ["3", "4"]])
        try:
            SimpleDocTemplate(str(out_path), pagesize=A4).build([Table(data)])
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}

    def with_image(self, image_path: str, caption: str = "Embedded image", out_dir: str | None = None) -> dict[str, Any]:
        """Build a real PDF embedding a real image file."""
        src = Path(image_path)
        if not src.exists():
            return {"ok": False, "error": f"image not found: {image_path}"}
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "with_image.pdf"
        styles = getSampleStyleSheet()
        try:
            story = [Paragraph(caption, styles["Heading2"]), RLImage(str(src), width=300, height=180)]
            SimpleDocTemplate(str(out_path), pagesize=A4).build(story)
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}


class PdfSuiteConnector:
    """Adapter: PdfSuite through the Connector protocol (dispatch by operation)."""

    def __init__(self, suite: PdfSuite | None = None) -> None:
        self._suite = suite if suite is not None else PdfSuite()

    def connect(self, spec: Any, params: dict[str, Any]) -> ConnectorResult:
        operation = params.get("operation", "document") or "document"
        method = {
            "document": lambda: self._suite.document(
                params.get("title", "Universal Mind Report"),
                params.get("sections"),
            ),
            "table": lambda: self._suite.table(params.get("headers"), params.get("rows")),
            "with_image": lambda: self._suite.with_image(
                params.get("image_path", ""), params.get("caption", "Embedded image")
            ),
        }.get(operation)
        if method is None:
            return ConnectorResult(ok=False, output=None, error=f"unknown operation: {operation!r}")
        result = method()
        if result.get("ok") is not True:
            return ConnectorResult(ok=False, output=None, error=result.get("error", "failed"))
        return ConnectorResult(
            ok=True,
            output={"path": result.get("path"), "bytes": result.get("bytes")},
        )


__all__ = ["PdfSuite", "PdfSuiteConnector"]