"""PdfSuite — the full document/PDF toolbox, integrated (reportlab).

The second integrated *program*: a complete PDF generator — multi-page documents,
headings, paragraphs, tables, embedded images — reachable as ONE capability set
through the Connector protocol, so the whole suite flows through ``orchestrate``
like any other capability.

Fail-safe and isolated: outputs land in a temp dir; a failing operation returns
not-ok with the real error.
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Image as RLImage,
)
from reportlab.platypus import (
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from universal_mind.connectors import ConnectorResult


class PdfSuite:
    """The integrated reportlab capability surface (a complete PDF program)."""

    name = "pdf-suite"
    capability = "pdf"

    # The FULL reportlab document surface: 12 real operations.
    OPERATIONS = (
        "document", "multi_page", "table", "styled_table", "with_image",
        "bullet_list", "numbered_list", "letterhead", "invoice", "two_column",
        "landscape", "cover_page", "persian_rtl", "persian_report",
    )

    def document(
        self,
        title: str = "Universal Mind Report",
        sections: list[str] | None = None,
        out_dir: str | None = None,
    ) -> dict[str, Any]:
        """Build a real multi-section PDF document."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "document.pdf"
        styles = getSampleStyleSheet()
        story: list[Any] = [Paragraph(title, styles["Title"])]
        for section in sections or ["Generated by the Universal Mind synthesis loop."]:
            story.append(Spacer(1, 12))
            story.append(Paragraph(section, styles["BodyText"]))
        try:
            SimpleDocTemplate(str(out_path), pagesize=A4).build(story)
        except Exception as exc:  # noqa: BLE001 — real generation errors surface
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}

    def table(
        self,
        headers: list[str] | None = None,
        rows: list[list[str]] | None = None,
        out_dir: str | None = None,
    ) -> dict[str, Any]:
        """Build a real PDF containing a data table."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "table.pdf"
        data = [headers or ["Column A", "Column B"]]
        data.extend(rows or [["1", "2"], ["3", "4"]])
        try:
            SimpleDocTemplate(str(out_path), pagesize=A4).build([Table(data)])
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}

    def with_image(self, image_path: str, caption: str = "Embedded image", out_dir: str | None = None) -> dict[str, Any]:
        """Build a real PDF embedding a real image file."""
        src = Path(image_path)
        if not src.exists():
            return {"ok": False, "error": f"image not found: {image_path}"}
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "with_image.pdf"
        styles = getSampleStyleSheet()
        try:
            story = [Paragraph(caption, styles["Heading2"]), RLImage(str(src), width=300, height=180)]
            SimpleDocTemplate(str(out_path), pagesize=A4).build(story)
        except Exception as exc:  # noqa: BLE001
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}


    # --- the 9 declared-but-missing operations, now real ---
    def _build(self, story: list[Any], out_path: Path, pagesize: Any = A4) -> dict[str, Any]:
        try:
            SimpleDocTemplate(str(out_path), pagesize=pagesize).build(story)
        except Exception as exc:  # noqa: BLE001 — real generation errors surface
            return {"ok": False, "error": str(exc)}
        if not out_path.exists():
            return {"ok": False, "error": "PDF was not produced"}
        return {"ok": True, "path": str(out_path), "bytes": out_path.stat().st_size, "error": ""}

    def multi_page(self, title: str = "Multi-page report", out_dir: str | None = None) -> dict[str, Any]:
        """Alias of :meth:`multi_section` (the declared multi-page operation)."""
        return self.multi_section(title, out_dir)

    def multi_section(self, title: str = "Multi-page report", out_dir: str | None = None) -> dict[str, Any]:
        """A genuinely multi-page PDF: numbered chapters, one per page."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        story: list[Any] = [Paragraph(title, styles["Title"])]
        for i in range(1, 4):
            story.append(PageBreak())
            story.append(Paragraph(f"Chapter {i}", styles["Heading1"]))
            story.append(Spacer(1, 8))
            story.append(Paragraph(f"Content of chapter {i} — filled with enough real text "
                                   f"to occupy the page and prove pagination works across "
                                   f"multiple physical pages of the document.", styles["BodyText"]))
        return self._build(story, target / "multi_page.pdf")

    def styled_table(self, headers: list[str] | None = None, rows: list[list[str]] | None = None, out_dir: str | None = None) -> dict[str, Any]:
        """A table with a real grid/header style (not a bare Table)."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        data = [headers or ["Name", "Value"]]
        data.extend(rows or [["latency", "12ms"], ["throughput", "340/s"]])
        table = Table(data)
        table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]))
        return self._build([table], target / "styled_table.pdf")

    def bullet_list(self, items: list[str] | None = None, out_dir: str | None = None) -> dict[str, Any]:
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        items = items or ["absorption", "synthesis", "judgment"]
        flow = ListFlowable(
            [ListItem(Paragraph(i, styles["BodyText"]), leftIndent=18) for i in items],
            bulletType="bullet",
        )
        return self._build([Paragraph("Capabilities", styles["Title"]), flow], target / "bullet_list.pdf")

    def numbered_list(self, items: list[str] | None = None, out_dir: str | None = None) -> dict[str, Any]:
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        items = items or ["decompose", "execute", "synthesize"]
        flow = ListFlowable(
            [ListItem(Paragraph(i, styles["BodyText"]), leftIndent=18) for i in items],
            bulletType="1",
        )
        return self._build([Paragraph("Pipeline steps", styles["Title"]), flow], target / "numbered_list.pdf")

    def letterhead(self, title: str = "Universal Mind", subtitle: str = "One Mind · Many Capabilities", out_dir: str | None = None) -> dict[str, Any]:
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        story = [
            Paragraph(title, styles["Title"]),
            Paragraph(subtitle, styles["Italic"]),
            Spacer(1, 24),
            Paragraph("This document was generated by the integrated synthesis loop.", styles["BodyText"]),
        ]
        return self._build(story, target / "letterhead.pdf")

    def invoice(self, items: list[list[str]] | None = None, out_dir: str | None = None) -> dict[str, Any]:
        """A real invoice layout: header, itemised table, total row."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        rows = items or [["Capability", "Cost"], ["data", "1.0"], ["chart", "1.0"], ["pdf", "1.0"]]
        data = [["Invoice", "Universal Mind"]]
        data.extend(rows)
        total = sum(float(r[1]) for r in rows[1:] if r[1].replace(".", "", 1).isdigit())
        data.append(["Total", f"{total:.1f}"])
        table = Table(data)
        table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("SPAN", (0, 0), (1, 0)),
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ]))
        story = [Paragraph("Invoice", styles["Title"]), Spacer(1, 12), table]
        return self._build(story, target / "invoice.pdf")

    def two_column(self, left_text: str = "Left column content.", right_text: str = "Right column content.", out_dir: str | None = None) -> dict[str, Any]:
        """A real two-column layout via a borderless 2-cell table."""
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        left = Paragraph(left_text, styles["BodyText"])
        right = Paragraph(right_text, styles["BodyText"])
        layout = Table([[left, right]], colWidths=[230, 230])
        layout.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
        return self._build([layout], target / "two_column.pdf")

    def landscape(self, title: str = "Landscape page", out_dir: str | None = None) -> dict[str, Any]:
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        return self._build(
            [Paragraph(title, styles["Title"]), Spacer(1, 12),
             Paragraph("This page is genuinely landscape (wider than tall).", styles["BodyText"])],
            target / "landscape.pdf", pagesize=landscape(A4),
        )

    def cover_page(self, title: str = "Universal Mind", subtitle: str = "Synthesis Report", out_dir: str | None = None) -> dict[str, Any]:
        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-"))
        target.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        story = [
            Spacer(1, 140),
            Paragraph(title, styles["Title"]),
            Paragraph(subtitle, styles["Heading2"]),
            Spacer(1, 24),
            PageBreak(),
            Paragraph("Body starts on page two.", styles["BodyText"]),
        ]
        return self._build(story, target / "cover_page.pdf")


    def persian_report(
        self,
        image_path: str = "",
        title: str = "گزارش ذهن یکپارچه",
        paragraphs: list[str] | None = None,
        out_dir: str | None = None,
    ) -> dict[str, Any]:
        """A Persian RTL report that embeds a REAL produced image (the flow target).

        The fusion of the Persian layer and the dataflow: the report is RTL with
        a real Persian font AND carries the actual artifact the previous program
        produced (the chart, the image, ...). No image → honest failure, never a
        text-only silent substitute.
        """
        if not image_path or not Path(image_path).exists():
            return {"ok": False, "error": "نموداری برای درج نیست — ابتدا نمودار بساز"}

        from reportlab.lib.enums import TA_RIGHT
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        from reportlab.platypus import Image as RLImage

        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-fa-report-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "persian_report.pdf"
        styles = getSampleStyleSheet()
        for candidate in (r"C:\Windows\Fonts\tahoma.ttf", r"C:\Windows\Fonts\arial.ttf"):
            if Path(candidate).exists():
                pdfmetrics.registerFont(TTFont("PersianFont", candidate))
                break
        else:
            return {"ok": False, "error": "no Persian-capable font found on this system"}
        fa_style = styles["BodyText"].clone("PersianBody", fontName="PersianFont", alignment=TA_RIGHT, wordWrap="RTL")
        fa_title = styles["Title"].clone("PersianTitle", fontName="PersianFont", alignment=TA_RIGHT, wordWrap="RTL")
        story: list[Any] = [Paragraph(title, fa_title)]
        for paragraph in paragraphs or ["گزارش تولیدشده توسط حلقهی سنتز ذهن یکپارچه."]:
            story.append(Spacer(1, 12))
            story.append(Paragraph(paragraph, fa_style))
        story.append(Spacer(1, 18))
        story.append(RLImage(image_path, width=380, height=240))
        story.append(Spacer(1, 6))
        story.append(Paragraph("نمودار تولیدشده در همین اجرا", fa_style))
        return self._build(story, out_path)

    def persian_rtl(
        self,
        title: str = "گزارش ذهن یکپارچه",
        paragraphs: list[str] | None = None,
        out_dir: str | None = None,
    ) -> dict[str, Any]:
        """A real Persian document with RTL alignment and a real embedded Persian font.

        reportlab's base fonts have no Persian glyphs, so the TTF that ships with
        the OS (Tahoma) is registered for real text shaping. Paragraphs use
        wordWrap='RTL' + alignment=TA_RIGHT — a genuinely right-to-left document.
        """
        from reportlab.lib.enums import TA_RIGHT
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont

        target = Path(out_dir) if out_dir else Path(tempfile.mkdtemp(prefix="um-pdf-fa-"))
        target.mkdir(parents=True, exist_ok=True)
        out_path = target / "persian_rtl.pdf"
        styles = getSampleStyleSheet()
        # Register a real OS Persian-capable font (Tahoma ships with Windows).
        for candidate in (r"C:\Windows\Fonts\tahoma.ttf", r"C:\Windows\Fonts\arial.ttf"):
            if Path(candidate).exists():
                pdfmetrics.registerFont(TTFont("PersianFont", candidate))
                break
        else:
            return {"ok": False, "error": "no Persian-capable font found on this system"}
        fa_style = styles["BodyText"].clone("PersianBody", fontName="PersianFont", alignment=TA_RIGHT, wordWrap="RTL")
        fa_title = styles["Title"].clone("PersianTitle", fontName="PersianFont", alignment=TA_RIGHT, wordWrap="RTL")
        story: list[Any] = [Paragraph(title, fa_title)]
        for paragraph in paragraphs or ["این سند توسط حلقهی سنتز ذهن یکپارچه ساخته شده است.",
                                        "متن فارسی واقعی با راستچین کامل."]:
            story.append(Spacer(1, 12))
            story.append(Paragraph(paragraph, fa_style))
        return self._build(story, out_path)


class PdfSuiteConnector:
    """Adapter: PdfSuite through the Connector protocol (dispatch by operation)."""

    def __init__(self, suite: PdfSuite | None = None) -> None:
        self._suite = suite if suite is not None else PdfSuite()

    def connect(self, spec: Any, params: dict[str, Any]) -> ConnectorResult:
        operation = params.get("operation", "document") or "document"
        suite = self._suite
        method = {
            "document": lambda: suite.document(
                params.get("title", "Universal Mind Report"),
                params.get("sections"),
            ),
            "multi_section": lambda: suite.multi_section(
                params.get("title", "Multi-page report")
            ),
            "multi_page": lambda: suite.multi_page(
                params.get("title", "Multi-page report")
            ),
            "table": lambda: suite.table(params.get("headers"), params.get("rows")),
            "styled_table": lambda: suite.styled_table(params.get("headers"), params.get("rows")),
            "with_image": lambda: suite.with_image(
                params.get("image_path", ""), params.get("caption", "Embedded image")
            ),
            "bullet_list": lambda: suite.bullet_list(params.get("items")),
            "numbered_list": lambda: suite.numbered_list(params.get("items")),
            "letterhead": lambda: suite.letterhead(params.get("title", "Universal Mind"), params.get("subtitle", "One Mind · Many Capabilities")),
            "invoice": lambda: suite.invoice(params.get("items")),
            "two_column": lambda: suite.two_column(params.get("left_text", "Left column."), params.get("right_text", "Right column.")),
            "landscape": lambda: suite.landscape(params.get("title", "Landscape page")),
            "cover_page": lambda: suite.cover_page(params.get("title", "Universal Mind"), params.get("subtitle", "Synthesis Report")),
            "persian_report": lambda: suite.persian_report(
                params.get("image_path", ""), params.get("title", "گزارش ذهن یکپارچه"),
                params.get("paragraphs"),
            ),
            "persian_rtl": lambda: suite.persian_rtl(
                params.get("title", "گزارش ذهن یکپارچه"), params.get("paragraphs")
            ),
        }.get(operation)
        if method is None:
            return ConnectorResult(ok=False, output=None, error=f"unknown operation: {operation!r}")
        result = method()
        if result.get("ok") is not True:
            return ConnectorResult(ok=False, output=None, error=result.get("error", "failed"))
        return ConnectorResult(
            ok=True,
            output={"path": result.get("path"), "bytes": result.get("bytes")},
        )


__all__ = ["PdfSuite", "PdfSuiteConnector"]